# -*- coding: utf-8 -*-
"""youtube.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzEinahvEfRB3CR-dHohdlG5Jwpt4BEW
"""

from googleapiclient.discovery import build

api_key = "AIzaSyCXYg3ueLZkMjtyF67N1RM2QjvZtNBVSe8"


youtube = build("youtube", "v3", developerKey=api_key)

search_response = youtube.search().list(
    part="id",
    q="J-POP",
    type="video",
    videoCategoryId="10",   # 音楽に限定
    maxResults=100
).execute()
video_ids = [item["id"]["videoId"] for item in search_response["items"]]

video_response = youtube.videos().list(
    part="snippet,statistics,contentDetails",
    id=",".join(video_ids)
).execute()

import pandas as pd

rows = []

for item in video_response["items"]:
    rows.append({
        "title": item["snippet"]["title"],
        "channel": item["snippet"]["channelTitle"],
        "views": int(item["statistics"]["viewCount"]),
        "likes": int(item["statistics"].get("likeCount", 0)),
        "comments": int(item["statistics"].get("commentCount", 0)),
        "published": item["snippet"]["publishedAt"],
        "duration":item["contentDetails"]["duration"]
    })

df = pd.DataFrame(rows)
df.sort_values("views", ascending=False)

correlation_data = {
    'Metrics': ['再生回数と高評価数', '再生回数とコメント数', '再生回数と動画時間', '再生回数と公開日時'],
    'Correlation Coefficient': [
        correlation, # From previous calculation df_compare['views'].corr(df_compare['likes'])
        correlation_comments_views,
        correlation_duration_views,
        correlation_published_views
    ]
}

correlation_df = pd.DataFrame(correlation_data)
display(correlation_df)

correlation = df_compare['views'].corr(df_compare['likes'])
print(f"再生回数と高評価数の相関係数: {correlation:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns
import japanize_matplotlib # 日本語表示のため

# グラフ1: 再生回数 vs 高評価数
plt.figure(figsize=(10, 6))
sns.scatterplot(x='likes', y='views', data=df)
plt.title('再生回数と高評価数の相関')
plt.xlabel('高評価数')
plt.ylabel('再生回数')
plt.grid(True)
plt.show()

correlation_comments_views = df['views'].corr(df['comments'])
print(f"再生回数とコメント数の相関係数: {correlation_comments_views:.2f}")

# グラフ2: 再生回数 vs コメント数
plt.figure(figsize=(10, 6))
sns.scatterplot(x='comments', y='views', data=df)
plt.title('再生回数とコメント数の相関')
plt.xlabel('コメント数')
plt.ylabel('再生回数')
plt.grid(True)
plt.show()

import re

def parse_duration(duration_str):
    # ISO 8601 duration parser
    # Example: PT2M32S -> 152 seconds
    total_seconds = 0
    if 'H' in duration_str:
        hours = int(re.search(r'(\d+)H', duration_str).group(1))
        total_seconds += hours * 3600
    if 'M' in duration_str:
        minutes = int(re.search(r'(\d+)M', duration_str).group(1))
        total_seconds += minutes * 60
    if 'S' in duration_str:
        seconds = int(re.search(r'(\d+)S', duration_str).group(1))
        total_seconds += seconds
    return total_seconds

df['duration_seconds'] = df['duration'].apply(parse_duration)

correlation_duration_views = df['views'].corr(df['duration_seconds'])
print(f"再生回数と動画時間の相関係数: {correlation_duration_views:.2f}")

# グラフ3: 再生回数 vs 動画時間 (秒)
plt.figure(figsize=(10, 6))
sns.scatterplot(x='duration_seconds', y='views', data=df)
plt.title('再生回数と動画時間の相関')
plt.xlabel('動画時間 (秒)')
plt.ylabel('再生回数')
plt.grid(True)
plt.show()

df['published_datetime'] = pd.to_datetime(df['published'])
df['published_timestamp'] = df['published_datetime'].apply(lambda x: x.timestamp())

correlation_published_views = df['views'].corr(df['published_timestamp'])
print(f"再生回数と公開日時の相関係数: {correlation_published_views:.2f}")

# グラフ4: 再生回数 vs 公開日時
plt.figure(figsize=(10, 6))
sns.scatterplot(x='published_datetime', y='views', data=df)
plt.title('再生回数と公開日時の相関')
plt.xlabel('公開日時')
plt.ylabel('再生回数')
plt.grid(True)
plt.show()