# -*- coding: utf-8 -*-
"""Youtube2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ui3fzDZgkprKnmKjVUrgw0693B0sbk2t
"""

# Commented out IPython magic to ensure Python compatibility.
#ライブラリのインポート
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
# %matplotlib inline
sns.set()

#機械学習ライブラリ
import sklearn

#小数点第3位まで表示
# %precision 3

#グラフで日本語を使えるようにする
!pip install japanize_matplotlib
import japanize_matplotlib

import requests
import time
import re
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timezone
import numpy as np

API_KEY = "AIzaSyBbGxXKUGr00jzd_BhCxVMOz3chXlIDt90"
CHANNEL_ID = "UCUCeZaZeJbEYAAzvMgrKOPQ"


# ---------------------------
# duration → 秒
# ---------------------------
def parse_duration(duration):
    pattern = r'PT((\d+)H)?((\d+)M)?((\d+)S)?'
    match = re.match(pattern, duration)

    hours = int(match.group(2)) if match.group(2) else 0
    minutes = int(match.group(4)) if match.group(4) else 0
    seconds = int(match.group(6)) if match.group(6) else 0

    return hours * 3600 + minutes * 60 + seconds


# ---------------------------
# 音楽動画フィルタ
# ---------------------------
def is_music_video(title, duration):
    t = title.lower()

    if duration <= 60:
        return False

    if duration > 600:
        return False

    exclude = ["interview", "対談", "making", "behind", "teaser", "trailer"]
    if any(word in t for word in exclude):
        return False

    include = ["mv", "music video", "official"]
    if any(word in t for word in include):
        return True

    if 120 <= duration <= 480:
        return True

    return False


# ---------------------------
# API
# ---------------------------
def get_uploads_playlist_id(channel_id):
    url = "https://www.googleapis.com/youtube/v3/channels"
    return requests.get(url, params={
        "part": "contentDetails",
        "id": channel_id,
        "key": API_KEY
    }).json()["items"][0]["contentDetails"]["relatedPlaylists"]["uploads"]


def get_all_videos(playlist_id):
    videos = []
    token = None

    while True:
        res = requests.get(
            "https://www.googleapis.com/youtube/v3/playlistItems",
            params={
                "part": "snippet,contentDetails",
                "playlistId": playlist_id,
                "maxResults": 50,
                "pageToken": token,
                "key": API_KEY
            }
        ).json()

        for item in res["items"]:
            videos.append({
                "videoId": item["contentDetails"]["videoId"],
                "title": item["snippet"]["title"],
                "publishedAt": item["contentDetails"]["videoPublishedAt"]
            })

        token = res.get("nextPageToken")
        if not token:
            break

        time.sleep(0.1)

    return videos


def get_video_details(ids):
    return requests.get(
        "https://www.googleapis.com/youtube/v3/videos",
        params={
            "part": "contentDetails,statistics",
            "id": ",".join(ids),
            "key": API_KEY
        }
    ).json()


# ---------------------------
# データ収集
# ---------------------------
def collect_data():
    playlist_id = get_uploads_playlist_id(CHANNEL_ID)
    videos = get_all_videos(playlist_id)

    rows = []

    for i in range(0, len(videos), 50):
        batch = videos[i:i+50]
        ids = [v["videoId"] for v in batch]

        details = get_video_details(ids)

        for item in details["items"]:
            vid = item["id"]
            duration = parse_duration(item["contentDetails"]["duration"])
            meta = next(v for v in batch if v["videoId"] == vid)

            if not is_music_video(meta["title"], duration):
                continue

            stats = item.get("statistics", {})
            views = int(stats.get("viewCount", 0))
            likes = int(stats.get("likeCount", 0))

            rows.append({
                "title": meta["title"],
                "duration_sec": duration,
                "views": views,
                "likes": likes,
                "publishedAt": meta["publishedAt"]
            })

        time.sleep(0.1)

    df = pd.DataFrame(rows)

    # ---------------------------
    # 補正（重要）
    # ---------------------------
    df["publishedAt"] = pd.to_datetime(df["publishedAt"], utc=True)
    now = datetime.now(timezone.utc)

    df["days"] = (now - df["publishedAt"]).dt.days + 1
    df["views_per_day"] = df["views"] / df["days"]

    return df


# ---------------------------
# 可視化（改善版）
# ---------------------------
def visualize(df):

    # jitter（重なり対策）
    x = df["likes"] + np.random.normal(0, df["likes"].std()*0.01, len(df))
    y = df["views_per_day"]

    # ---------------------------
    # 散布図（改善版）
    # ---------------------------
    plt.figure()

    plt.scatter(
        x,
        y,
        alpha=0.2,
        s=8
    )

    plt.xscale("log")
    plt.yscale("log")

    plt.xlabel("高評価数（log）")
    plt.ylabel("1日あたり再生回数（log）")
    plt.title("高評価 vs 再生効率")

    plt.show()


# ---------------------------
# 分析
# ---------------------------
def analyze(df):
    print("\n==== 相関係数 ====")
    print(df[["duration_sec", "likes", "views_per_day"]].corr())

    print("\n==== 再生効率ランキング ====")
    print(
        df.sort_values("views_per_day", ascending=False)[
            ["title", "views_per_day", "views"]
        ].head(10)
    )

# ---------------------------
# 動画時間 vs 再生効率（回帰線なし）
# ---------------------------
def analyze_duration(df):

    print("\n==== 動画時間 vs 再生効率 相関 ====")

    # 相関係数
    corr = df["duration_sec"].corr(df["views_per_day"])
    print("相関係数:", corr)

    # ---------------------------
    # 散布図（シンプル版）
    # ---------------------------
    plt.figure()

    plt.scatter(
        df["duration_sec"],
        df["views_per_day"],
        alpha=0.2,
        s=8
    )

    plt.yscale("log")   # これ重要

    plt.xlabel("動画時間（秒）")
    plt.ylabel("1日あたり再生回数（log）")
    plt.title("動画時間 vs 再生効率")

    plt.show()
# ---------------------------
# 実行
# ---------------------------
if __name__ == "__main__":
    df = collect_data()

    print("\nデータサンプル:")
    print(df.head())

    analyze(df)
    visualize(df)

    # ← 追加
    analyze_duration(df)